name: Test Mist

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
      options: --user 1001

    services:
      mariadb:
        image: mariadb:10.4
        env:
          MYSQL_USER: test_mist
          MYSQL_DATABASE: test_mist
          MYSQL_PASSWORD: test_mist
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test
        env: 
          DB_HOST: mariadb
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          TEST_DB_HOST: mariadb
          TEST_DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          TEST_DB_PASS: test_mist
          REDIS_HOST: redis
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
          PUBLIC_URL: localhost:8080
